### ISSUE TITLE
TinyLibrary/RapidJSON Not Distributed

### ISSUE THREAD

**Issue by yrrapt** [svancau/verilator#2]
The tiny library and rapidjson folders are empty which causes the build to fail.

I simply downloaded the repositories and placed the files in the respective folders but it would be nice if the documentation instructed this.

**Comment by svancau** [comment]
You can solve this problem by doing a recursive git clone.
`git clone --recursive`

If you already cloned use the following command to fetch all the submodules :
`it submodule update --init --recursive --remote`
